# Generated by Django 6.0.6 on 2026-06-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
    ]
