# Generated by Django 6.0.6 on 2026-06-16 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_initial"),
        ("plans", "0003_alter_membershipplan_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["status", "end_date"], name="membership_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["member", "status"], name="membership_member_status_idx"
            ),
        ),
    ]
