# Generated by Django 6.0.6 on 2026-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershipplan",
            options={
                "ordering": ["price"],
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
            },
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("STANDARD", "Standard"),
                    ("PREMIUM", "Premium"),
                ],
                max_length=10,
            ),
        ),
    ]
